
services:
  traefik:
    image: traefik:v2.9
    command:
      - traefik
      - --entrypoints.dev.address=:4050
      - --providers.file.filename=/config.yml
      - --api.insecure=true
    ports:
      - 4050:4050
      - 4051:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./lb.yml:/config.yml:ro
    networks:
      - traefik-network

  backend:
    image: '${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
    build:
      context: ./backend
    command: yarn dev
    ports:
      - "4055:9000"
      - "4052:7000"
      - "4053:7001"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    environment:
      - NODE_ENV=production
      - MEDUSA_ADMIN_CORS=*
      - MEDUSA_STORE_CORS=*
    networks:
      - traefik-network

  frontend:
    image: '${DOCKER_IMAGE_FRONTEND?Variable not set}:${TAG-latest}'
    build:
      context: ./frontend
    command: npm run dev
    ports:
      # - "3000:3000"
      - "4054:8000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - traefik-network

  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

networks:
  traefik-network:
    name: traefik-network
    external: true

volumes:
  frontend_node_modules:
  backend_node_modules:
